### ISSUE TITLE
The app doesn't appear on Google Play

### ISSUE THREAD

**Issue by lurecas** [linagee/cordova-androidpublisher#1]
Hi!
I've been using your plugin to publish an app to the Play Store. 

I've had to slightly modify it to be able to publish multiple APK per edit, because our app has two architectures (arm and x86). If I can make it work, I will make you a PR with my changes.

My problem is that I reach the end of the `async.waterfall` execution and it tells me that my app has been published on Google Play. Then I go to the APK section and the app is not any track.
I got a fully response object like this : `{ id: '14562834173185113058', expiryTimeSeconds: '1463756926' }` and intermediate objects like `[ { versionCode: 292,
    binary: { sha1: 'c16c4430b5cc1ff6da451ce53aa1330f006330f0' } } ]`

I've tested it also with one APK only, and the problem persists.
Any thoughts?
Thank you!

**Comment by linagee** [comment]
Thanks for finding some use in my open source contribution! A PR would be great!

Is this for a new app or to update an existing app?

**Comment by lurecas** [comment]
Hi!
No the app is an existing one. It's curious, because the new Google Play Console app notified me that an update was now live, but the APK are nowhere to be found. I'll have to try again..

**Comment by lurecas** [comment]
Have you used this plugin lately?

**Comment by linagee** [comment]
I haven't used it lately. It's possible something broke.
